# Generated by Django 3.2.14 on 2022-07-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_add_order_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['excel_id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='excel_id',
        ),
    ]
